:apiname: Loot API

= {apiname} Reference
SenorPez;
:doctype: book
:icons: font
:source-highlighter: highlight.js
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
== Overview

[[overview-versions]]
=== Versions

There is only a single version of {apiname}.

.{apiname} Versions
|===
| API Version | Accept Header

| Version 2.0.0
| `application/hal+json`
|===

[[overview-http-methods]]
=== HTTP Methods

The following HTTP methods are compatible with {apiname}.

.Supported HTTP Methods
|===
| Method | Usage

| `GET`
| Used to retrieve a resource.
|===

[[overview-http-status-codes]]
=== HTTP Status Codes

Requests to {apiname} return the following HTTP status codes.

.HTTP Status Codes
|===
| Status Code | Usage

| `200 OK`
| The `GET` request succeeded. The requested resource is returned in the response.

| `402 Payment Required`
| This code is erserved for when I need extra money.
|===

[[overview-hypermedia]]
=== Hypermedia

{apiname} conforms to the http://stateless.co/hal_specification.html[Hypertext Application Language (HAL)] standard.

* Resources are represented by key-value pairs.
* Collections of resources are contained in an `_embedded` field. Fields of embedded resources may be transformed or omitted.
** Embedded resources contains a `_links` field with a `self` link to access that resource. Other `_links` fields may be transformed or omitted.
* Links to other resources are contained in a `_links` field.
** Users should not create URIs but use the `_links` fields to navigate the API.
** Some resources may be respresented by multiple `_links` values depending on the position in the API hierarchy. With the exception of the `_links` field, these resources are identical regardless of the path used to reach them.

== Loot Resources
[[resources-loot-root]]
=== Root

The root endpoint supports the following methods:
|===
| Method | Description

| <<resources-loot-root-get, GET>>
| Provides a list of root resources.
|===

[[resources-loot-root-get]]
==== GET

Provides a list of root resources.

.Request Headers

include::{snippets}/index/request-headers.adoc[]

.Response Headers

include::{snippets}index/response-headers.adoc[]

.Response Links

include::{snippets}/index/links.adoc[]